parameters:
    koala_content.menu_provider.class: Koala\ContentBundle\Menu\EntityMenuProvider
    koala_content.menu_provider.entity: 'KoalaContentBundle:MenuItem'
    koala_content.menu_factory.class: Koala\ContentBundle\Menu\ContentAwareMenuFactory

    koala_content.route_repository.class: Koala\ContentBundle\Entity\RouteRepository
    koala_content.route_repository.entity: 'KoalaContentBundle:Route'
    koala_content.dynamic_router.class: Symfony\Cmf\Bundle\RoutingExtraBundle\Routing\DynamicRouter
    koala_content.mapper_page_controller.class: Symfony\Cmf\Component\Routing\Mapper\ControllerClassMapper
    koala_content.mapper_page_controller.controller: 'KoalaContentBundle:Page:show'

    koala_content.model.menu_item.class: Koala\ContentBundle\Entity\MenuItem
    koala_content.model.page.class: Koala\ContentBundle\Entity\Page
    koala_content.model.route.class: Koala\ContentBundle\Entity\Route
    koala_content.model.region.class: Koala\ContentBundle\Entity\Region

services:
    koala_content.menu_provider:
        class: %koala_content.menu_provider.class%
        arguments:
            - @service_container
            - @koala_content.menu_factory
            - @doctrine.orm.default_entity_manager
            - %koala_content.menu_provider.entity%
        tags:
            - { name: knp_menu.provider }

    koala_content.menu_factory:
        class: %koala_content.menu_factory.class%
        arguments:
            - @service_container
            - @router
            - @router 
            - koala_content.content_key

    koala_content.route_repository:
        class: %koala_content.route_repository.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - %koala_content.route_repository.entity%

    koala_content.mapper_page_controller:
        class: %koala_content.mapper_page_controller.class%
        arguments:
            - %koala_content.model.page.class%: %koala_content.mapper_page_controller.controller%

    koala_content.dynamic_router:
        class: %koala_content.dynamic_router.class%
        arguments:
            - @koala_content.route_repository
        calls:
            - [ setContext, [@router.request_context]]
            - [ setContainer, [@service_container]]
            - [ addControllerMapper, [@koala_content.mapper_page_controller]]

    koala_content.page_manager:
        class: %koala_content.page_manager.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - %koala_content.model.page.class%
            - %koala_content.model.route.class%

    koala_content.route_manager:
        class: %koala_content.route_manager.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - %koala_content.model.route.class%

    koala_content.menu_item_manager:
        class: %koala_content.menu_item_manager.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - %koala_content.model.menu_item.class%

    koala_content.region_manager:
        class: %koala_content.region_manager.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - %koala_content.model.region.class%
