parameters:
    koala_content.layouts_form_type.class: Koala\ContentBundle\Type\LayoutsFormType
    koala_content.layouts_provider.class: Koala\ContentBundle\LayoutsProvider
    koala_content.layouts_provider.layouts:
        default: {name: Default Layout, template: 'KoalaContentBundle:Layouts:default.html.twig'}

    koala_content.mercury_twig_extension.class: Koala\ContentBundle\Twig\MercuryExtension
    koala_content.mercury_twig_extension.template: 'KoalaContentBundle::mercury_region.html.twig'
    koala_content.mercury_twig_extension.defaults: {tag: 'div', default: ''}
    koala_content.mercury_twig_extension.package:
        javascripts:
            - mercury/javascripts/mercury.min.js
            - mercury/javascripts/mercury_dialogs.js
            - bundles/koalacontent/js/mercury_plugin.js
        stylesheets:
            - mercury/stylesheets/mercury.bundle.css
            - bundles/koalacontent/css/mercury_plugin.css

    koala_content.page_manager.class: Koala\ContentBundle\Doctrine\PageManager
    koala_content.route_manager.class: Koala\ContentBundle\Doctrine\RouteManager
    koala_content.menu_item_manager.class: Koala\ContentBundle\Doctrine\MenuItemManager
    koala_content.region_manager.class: Koala\ContentBundle\Doctrine\RegionManager

    koala_content.menu_item.form.type.class: Koala\ContentBundle\Type\MenuItemType
    koala_content.page.form.type.class: Koala\ContentBundle\Type\PageType
    koala_content.route.form.type.class: Koala\ContentBundle\Type\RouteType
            
services:
    koala_content.layouts_provider:
        class: %koala_content.layouts_provider.class%
        arguments:
            - %koala_content.layouts_provider.layouts%
    koala_content.layouts_form_type:
        class: %koala_content.layouts_form_type.class%
        arguments:
            - @koala_content.layouts_provider
        tags:
            - { name: form.type, alias: layouts }
    koala_content.mercury_twig_extension:
        class: %koala_content.mercury_twig_extension.class%
        arguments:
            - %koala_content.mercury_twig_extension.template%
            - %koala_content.mercury_twig_extension.defaults%
            - %koala_content.mercury_twig_extension.package%
        tags:
            - { name: twig.extension }

    koala_content.menu_item.form.type:
        class: %koala_content.menu_item.form.type.class%
        arguments: [%koala_content.model.menu_item.class%]
        tags:
            - { name: form.type, alias: menuItem }

    koala_content.page.form.type:
        class: %koala_content.page.form.type.class%
        arguments: [%koala_content.model.page.class%]
        tags:
            - { name: form.type, alias: page }

    koala_content.route.form.type:
        class: %koala_content.route.form.type.class%
        arguments: [%koala_content.model.route.class%]
        tags:
            - { name: form.type, alias: route }

    koala_content.model.page:
        class: %koala_content.model.page.class%
        factory_service: koala_content.page_manager
        factory_method: createPage

    koala_content.model.menu_item:
        class: %koala_content.model.menu_item.class%
        factory_service: koala_content.menu_item_manager
        factory_method: createMenuItem
        arguments:
            - @koala_content.model.page

    koala_content.menu_item.form.new:
        parent: koala_content.menu_item.form.edit
        arguments:
            - @koala_content.model.menu_item

    koala_content.menu_item.form.edit:
        class: Symfony\Component\Form\Form
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - menuItem
            - @koala_content.menu_item.form.type
