parameters:
    layouts_form_type.class: Koala\ContentBundle\Type\LayoutsFormType
    layouts_provider.class: Koala\ContentBundle\LayoutsProvider
    layouts_provider.layouts:
        default: {name: Default Layout, template: 'KoalaContentBundle:Layouts:default.html.twig'}
    mercury_twig_extension.class: Koala\ContentBundle\Twig\MercuryExtension
    mercury_twig_extension.template: 'KoalaContentBundle::mercury_region.html.twig'
    mercury_twig_extension.defaults: {tag: 'div', default: ''}
    mercury_twig_extension.package:
        javascripts:
            - mercury/javascripts/mercury.min.js
            - mercury/javascripts/mercury_dialogs.js
            - bundles/koalacontent/js/mercury_plugin.js
        stylesheets:
            - mercury/stylesheets/mercury.bundle.css
            - bundles/koalacontent/css/mercury_plugin.css

    koala_content.page_manager.class: Koala\ContentBundle\Doctrine\PageManager
    koala_content.route_manager.class: Koala\ContentBundle\Doctrine\RouteManager
    koala_content.menu_item_manager.class: Koala\ContentBundle\Doctrine\MenuItemManager
    koala_content.region_manager.class: Koala\ContentBundle\Doctrine\RegionManager

services:
    layouts_provider:
        class: %layouts_provider.class%
        arguments:
            - %layouts_provider.layouts%
    layouts_form_type:
        class: %layouts_form_type.class%
        arguments:
            - @layouts_provider
        tags:
            - { name: form.type, alias: layouts }
    mercury_twig_extension:
        class: %mercury_twig_extension.class%
        arguments:
            - %mercury_twig_extension.template%
            - %mercury_twig_extension.defaults%
            - %mercury_twig_extension.package%
        tags:
            - { name: twig.extension }

    koala_content.menuItem.form.type:
        class: Koala\ContentBundle\Type\MenuItemType
        arguments: [%koala_content.model.menuItem.class%]
        tags:
            - { name: form.type, alias: menuItem }

    koala_content.page.form.type:
        class: Koala\ContentBundle\Type\PageType
        arguments: [%koala_content.model.page.class%]
        tags:
            - { name: form.type, alias: page }

    koala_content.route.form.type:
        class: Koala\ContentBundle\Type\RouteType
        arguments: [%koala_content.model.route.class%]
        tags:
            - { name: form.type, alias: route }

    koala_content.model.page:
        class: %koala_content.model.page.class%
        factory_service: koala_content.page_manager
        factory_method: createPage

    koala_content.model.menuItem:
        class: %koala_content.model.menuItem.class%
        factory_service: koala_content.menu_item_manager
        factory_method: createMenuItem
        arguments:
            - @koala_content.model.page

    koala_content.menuItem.form.new:
        parent: koala_content.menuItem.form.edit
        arguments:
            - @koala_content.model.menuItem

    koala_content.menuItem.form.edit:
        class: Symfony\Component\Form\Form
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - menuItem
            - @koala_content.menuItem.form.type
